### ISSUE TITLE
Upload to supermarket

### ISSUE THREAD

**Issue by predominant** [rosstimson/chef-terraform#19]
Hey @rosstimson , the current 0.5.0 release of this cookbook is broken since the download location change from Hashicorp.

Can we release an updated version to the supermarket?

Thanks 🏆

**Comment by haidangwa** [comment]
@predominant I'm not sure what you mean, as the cookbook attributes default to https://releases.hashicorp.com/terraform for downloads of the code. That site is still valid.

**Comment by predominant** [comment]
Looks like 0.5.1 is now on supermarket. Thats all I was looking for really. Cheers 👍
