### ISSUE TITLE
Ark dependency is too old, it's preventing to use the latest version for this cookbook

### ISSUE THREAD

**Issue by jujugrrr** [rosstimson/chef-terraform#23]
Hi,
Because the ark dependency is on 1.1, we cannot use this cookbook if another cookbook depends of the 2+ ark version in our runlist.

Is there any reason why we need ark < 2.0?

https://github.com/rosstimson/chef-terraform/blob/master/metadata.rb#L10

Thank you

**Comment by haidangwa** [comment]
This is a reasonable request. I am working on a branch with other enhancements, so I'll fold this into what I'm currently working on, as well.

**Comment by jujugrrr** [comment]
👍

**Comment by bpoland** [comment]
Could you change attributes/default.rb so that the kernel['machine'] reference is node['kernel']['machine'] instead?  Otherwise you get a warning "method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13"

**Comment by haidangwa** [comment]
@bpoland fixed that in e3daadc2

**Comment by haidangwa** [comment]
Fixed in #24

**Comment by bpoland** [comment]
@haidangwa thanks!
