### ISSUE TITLE
URL should not assume filename naming convention

### ISSUE THREAD

**Issue by haidangwa** [rosstimson/chef-terraform#6]
Can we turn the filename of the zip file into a configurable node attribute? We store our artifacts in a private Nexus repo, which gets renamed to a file with dashes (`-`) instead of underscores. https://github.com/rosstimson/chef-terraform/blob/master/recipes/default.rb#L24 prevents any override of this without using something like chef-rewind.

**Comment by rosstimson** [comment]
This should present now thanks to you work, thanks very much.

**Comment by haidangwa** [comment]
Thanks for merging the code. Would you mind uploading it to Chef's
Supermarket? Since you aren't working with Chef much anymore, do you mind
adding me as a collaborator? I could carry the torch, per se.

**Comment by rosstimson** [comment]
@haidangwa I've just pushed to the Supermarket now.  

That would be awesome, thanks for the offer/help, I've added you as a collaborator.
